export const products = [
  {
      id: 'fmakjl7m0rcem6lytdkakmrz',
      title: "MEN'S SOLAR ROOF TEE",
      price: 20,
      image: '/1703767-00-A_0_2000.jpeg',
      description: 'INSPIRED BY OUR FULLY INTEGRATED HOME SOLAR AND STORAGE SYSTEM, THE TESLA SOLAR ROOF TEE ADVOCATES FOR CLEAN, SUSTAINABLE ENERGY WHEREVER YOU GO. DESIGNED FOR FIT, COMFORT AND STYLE, THE TEE FEATURES AN AERIAL VIEW OF OUR SEAMLESS SOLAR ROOF DESIGN ON THE FRONT WITH OUR SIGNATURE T LOGO ABOVE "SOLAR ROOF" ON THE BACK. MADE FROM 100% PERUVIAN COTTON.'
  },
  {
      id: 'ot5tsercf556bpvb3hnmmv6o',
      title: "MEN'S AI DAY TEE",
      price: 35,
      image: '/1905127-00-A_0_2000.jpeg',
      description: 'INSPIRED BY OUR FULLY INTEGRATED HOME SOLAR AND STORAGE SYSTEM, THE TESLA SOLAR ROOF TEE ADVOCATES FOR CLEAN, SUSTAINABLE ENERGY WHEREVER YOU GO. DESIGNED FOR FIT, COMFORT AND STYLE, THE TEE FEATURES AN AERIAL VIEW OF OUR SEAMLESS SOLAR ROOF DESIGN ON THE FRONT WITH OUR SIGNATURE T LOGO ABOVE "SOLAR ROOF" ON THE BACK. MADE FROM 100% PERUVIAN COTTON.'
  },
  {
      id: 'io2gcwyf96i3dl3kc4empml3',
      title: "MEN'S 3D LARGE WORDMARK TEE",
      price: 30,
      image: '/8764727-00-A_0_2000.jpeg',
      description: 'INSPIRED BY OUR FULLY INTEGRATED HOME SOLAR AND STORAGE SYSTEM, THE TESLA SOLAR ROOF TEE ADVOCATES FOR CLEAN, SUSTAINABLE ENERGY WHEREVER YOU GO. DESIGNED FOR FIT, COMFORT AND STYLE, THE TEE FEATURES AN AERIAL VIEW OF OUR SEAMLESS SOLAR ROOF DESIGN ON THE FRONT WITH OUR SIGNATURE T LOGO ABOVE "SOLAR ROOF" ON THE BACK. MADE FROM 100% PERUVIAN COTTON.'
  },
  {
      id: 'jxh1ditibolrprs52ovilblb',
      title: "MEN’S CYBERTRUCK HORIZON TEE",
      price: 35,
      image: '/1932712-00-A_1_2000.jpeg',
      description: 'INSPIRED BY OUR FULLY INTEGRATED HOME SOLAR AND STORAGE SYSTEM, THE TESLA SOLAR ROOF TEE ADVOCATES FOR CLEAN, SUSTAINABLE ENERGY WHEREVER YOU GO. DESIGNED FOR FIT, COMFORT AND STYLE, THE TEE FEATURES AN AERIAL VIEW OF OUR SEAMLESS SOLAR ROOF DESIGN ON THE FRONT WITH OUR SIGNATURE T LOGO ABOVE "SOLAR ROOF" ON THE BACK. MADE FROM 100% PERUVIAN COTTON.'
  },
  {
      id: 'fy17nrh2mys7sxssmst1nji7',
      title: 'RELAXED T LOGO HAT',
      price: 30,
      image: '/1857705-00-A_0_2000.jpeg',
      description: 'INSPIRED BY OUR FULLY INTEGRATED HOME SOLAR AND STORAGE SYSTEM, THE TESLA SOLAR ROOF TEE ADVOCATES FOR CLEAN, SUSTAINABLE ENERGY WHEREVER YOU GO. DESIGNED FOR FIT, COMFORT AND STYLE, THE TEE FEATURES AN AERIAL VIEW OF OUR SEAMLESS SOLAR ROOF DESIGN ON THE FRONT WITH OUR SIGNATURE T LOGO ABOVE "SOLAR ROOF" ON THE BACK. MADE FROM 100% PERUVIAN COTTON.'
  },
  {
      id: 'jkfkxt079bbvuspim6sp9drr',
      title: 'T LOGO CUFFED BEANIE',
      price: 20,
      image: '/1740407-00-A_0_2000.jpeg',
      description: 'INSPIRED BY OUR FULLY INTEGRATED HOME SOLAR AND STORAGE SYSTEM, THE TESLA SOLAR ROOF TEE ADVOCATES FOR CLEAN, SUSTAINABLE ENERGY WHEREVER YOU GO. DESIGNED FOR FIT, COMFORT AND STYLE, THE TEE FEATURES AN AERIAL VIEW OF OUR SEAMLESS SOLAR ROOF DESIGN ON THE FRONT WITH OUR SIGNATURE T LOGO ABOVE "SOLAR ROOF" ON THE BACK. MADE FROM 100% PERUVIAN COTTON.'
  },
  {
      id: 'sb69ehogwe24kzqewy55rx11',
      title: "MEN'S PLAID MODE TEE",
      price: 20,
      image: '/1549268-00-A_0_2000.jpeg',
      description: 'INSPIRED BY OUR FULLY INTEGRATED HOME SOLAR AND STORAGE SYSTEM, THE TESLA SOLAR ROOF TEE ADVOCATES FOR CLEAN, SUSTAINABLE ENERGY WHEREVER YOU GO. DESIGNED FOR FIT, COMFORT AND STYLE, THE TEE FEATURES AN AERIAL VIEW OF OUR SEAMLESS SOLAR ROOF DESIGN ON THE FRONT WITH OUR SIGNATURE T LOGO ABOVE "SOLAR ROOF" ON THE BACK. MADE FROM 100% PERUVIAN COTTON.'
  },
  {
      id: 'ely3x99pkylyfhdtet694jwa',
      title: "MEN'S BATTERY DAY TEE",
      price: 20,
      image: '/1633802-00-A_0_2000.jpeg',
      description: 'INSPIRED BY OUR FULLY INTEGRATED HOME SOLAR AND STORAGE SYSTEM, THE TESLA SOLAR ROOF TEE ADVOCATES FOR CLEAN, SUSTAINABLE ENERGY WHEREVER YOU GO. DESIGNED FOR FIT, COMFORT AND STYLE, THE TEE FEATURES AN AERIAL VIEW OF OUR SEAMLESS SOLAR ROOF DESIGN ON THE FRONT WITH OUR SIGNATURE T LOGO ABOVE "SOLAR ROOF" ON THE BACK. MADE FROM 100% PERUVIAN COTTON.'
  }
]

export const medias = [
    {
      id: 'ot5t456cf556bpvb3hghjk6o',
      url: '/8764806-00-A_0_2000.jpeg'
    },
    {
      id: 'io2g456f96i3dl3kc4ghjkl3',
      url: '/1741613-00-A_1_2000.jpeg'
    },
    {
      id: 'jxh1456ibolrprs52oghjklb',
      url: '/8764741-00-A_0_2000.jpeg'
    },
    {
      id: 'fy174562mys7sxssmsghjki7',
      url: '/7654420-00-A_0_2000.jpeg'
    },
    {
      id: 'jkfk45679bbvuspim6ghjkrr',
      url: '/8529205-00-A_0_2000.jpeg'
    },
    {
      id: 'fmakjl7m0rcem6lytdkakmrz',
      url: '/1703767-00-A_0_2000.jpeg'
    },
    {
      id: 'ot5tsercf556bpvb3hnmmv6o',
      url: '/1905127-00-A_0_2000.jpeg'
    },
    {
      id: 'io2gcwyf96i3dl3kc4empml3',
      url: '/8764727-00-A_0_2000.jpeg'
    },
    {
      id: 'jxh1ditibolrprs52ovilblb',
      url: '/1932712-00-A_1_2000.jpeg'
    },
    {
      id: 'fy17nrh2mys7sxssmst1nji7',
      url: '/1857705-00-A_0_2000.jpeg'
    },
    {
      id: 'jkfkxt079bbvuspim6sp9drr',
      url: '/1740407-00-A_0_2000.jpeg'
    },
    {
      id: 'sb69ehogwe24kzqewy55rx11',
      url: '/1549268-00-A_0_2000.jpeg'
    },
    {
      id: 'ely3x99pkylyfhdtet694jwa',
      url: '/1633802-00-A_0_2000.jpeg'
    }
]